#ifndef APP_SCREEN_H
#define APP_SCREEN_H

#define APP_SCREEN_SPLASH 0
#define APP_SCREEN_GAME 1
#define APP_SCREEN_HIGHSCORE 2
#define APP_SCREEN_RESUME 4
#define APP_SCREEN_MENU 5
#define APP_SCREEN_DIFFICULTY_SELECT 6


#endif /* app/screen.h */
